### PR TITLE
Add connection string

### PR DESCRIPTION
**Pull request by pvanbuijtene**
Adds the possibility to create a client configuration using a connection string.

Currently `DiscoveryInterval` and `GossipTimeout` aren't used, can add this if it's easy to do otherwise I can remove them.

### CODE REVIEW

**Comment by pvanbuijtene** [comment]
The tests succeed locally, looks like somethings up with the CI build.
```
go test -v .
=== RUN   TestAppendToStreamSingleEventNoStream
--- PASS: TestAppendToStreamSingleEventNoStream (2.44s)
=== RUN   TestAppendWithInvalidStreamRevision
--- PASS: TestAppendWithInvalidStreamRevision (2.05s)
=== RUN   TestAppendToSystemStreamWithIncorrectCredentials
--- PASS: TestAppendToSystemStreamWithIncorrectCredentials (2.07s)
...
=== RUN   TestStreamSubscriptionDeliversAllEventsInStreamAndListensForNewEvents
--- PASS: TestStreamSubscriptionDeliversAllEventsInStreamAndListensForNewEvents (3.43s)
=== RUN   TestAllSubscriptionDeliversAllowsCancellationDuringStream
--- PASS: TestAllSubscriptionDeliversAllowsCancellationDuringStream (3.24s)
=== RUN   TestAllSubscriptionWithFilterDeliversCorrectEvents
--- PASS: TestAllSubscriptionWithFilterDeliversCorrectEvents (3.95s)
PASS
ok      github.com/EventStore/EventStore-Client-Go/client      37.956s
```

**Review by YoEight — COMMENTED** [review]
Thanks for your work!

Could you make sure your implementation work against those mockups?

https://github.com/EventStore/EventStoreDB-Client-Rust/blob/master/tests/fixtures/connection_string/mockups.toml

**Comment by pvanbuijtene** [comment]
@YoEight I added the extra tests, I skipped the one regarding the `esdb+discover://` scheme as I don't think it's currently implemented in this client.

**Comment by YoEight** [comment]
@pvanbuijtene Thanks for adding those tests. Would you reconsider your position on the last test? It is true that the go client doesn't support that feature yet. However, it will be added shortly.

**Comment by pvanbuijtene** [comment]
@YoEight aah ok, wasn't sure about adding features which are not supported yet, will add it.

**Comment by pvanbuijtene** [comment]
@YoEight I added the support for `esdb+discover://`.

**Review by hayley-jean — CHANGES_REQUESTED** [review]
Thanks for adding the discover protocol, there's just one issue I've found while testing locally.

It looks like the scheme needs to not be added to the address when parsing the hosts [here](https://github.com/EventStore/EventStore-Client-Go/pull/24/files#diff-fd4da0ae162998a44cb424b452bbc8b4b997c773856a030201af104bb1f59152R271).
When running with the connection string:

```
config, err := client.ParseConnectionString("esdb://admin:changeit@localhost:1113,localhost:2113?tls=true")
client, err := client.NewClient(config)
```

or

```
config, err := client.ParseConnectionString("esdb://admin:changeit@localhost:2113?tls=true")
client, err := client.NewClient(config)
```

I'm getting the error:

```
panic: Unexpected failure Failed to construct read client. Reason: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address https://localhost:2113: too many colons in address"
```

**Comment by pvanbuijtene** [comment]
@hayley-jean I will have a look at it today.

**Comment by pvanbuijtene** [comment]
@hayley-jean the scheme part is removed from the address and I replaced the existing config with the connection string to make it part of the tests.

The tests are locally succeeding so not sure if the build error is from my latest changes.

**Review by YoEight — APPROVED** [review]

**Comment by hayley-jean** [comment]
Thanks! The changes look good

**Review by hayley-jean — APPROVED** [review]

**Pull request merged**
