### PR TITLE
Implement channel-based persistent subscriptions.

### PR DESCRIPTION
**Pull request by YoEight**

### CODE REVIEW

**Comment by YoEight** [comment]
Docker containers are hit or miss
```
Starting docker container...
Started container with id: 98816dbb8c5f9c52b2a86d4751a2ca69fcf51f18e83cdfcd74198600f746dd70, name: /stoic_mahavira
panic: test timed out after 10m0s
```

**Comment by hayley-jean** [comment]
> Docker containers are hit or miss
> 
> ```
> Starting docker container...
> Started container with id: 98816dbb8c5f9c52b2a86d4751a2ca69fcf51f18e83cdfcd74198600f746dd70, name: /stoic_mahavira
> panic: test timed out after 10m0s
> ```

This might be a legitimate timeout in the test rather than the docker container. When running it locally, I don't seem to receive any events from the persistent subscription connection

**Review by pvanbuijtene — APPROVED** [review]

**Review by hayley-jean — APPROVED** [review]
Looks good! Just a quick question: Is there a way to dispose the subscription after subscribing?

**Comment by YoEight** [comment]
TODO: Expose the `Close` function to the persistent subscription interface

**Comment by YoEight** [comment]
Done @hayley-jean

**Review by hayley-jean — APPROVED** [review]

**Comment by YoEight** [comment]
@hayley-jean done

**Review by pvanbuijtene — APPROVED** [review]

**Pull request merged**
