### PR TITLE
feat: make stream not found error a variable

### PR DESCRIPTION
**Pull request by bweston92**
Changed: Steam not found error is now a variable

Currently having to compare on string value which is not the best developer experience in my opinion.

### CODE REVIEW

**Review by YoEight — APPROVED** [review]

**Comment by bweston92** [comment]
whoops, didn't see there was an errors package, would this error also be better in that? https://github.com/EventStore/EventStore-Client-Go/blob/master/errors/errors.go

**Comment by bweston92** [comment]
changed it for consistency

**Review by thefringeninja — APPROVED** [review]

**Comment by bweston92** [comment]
@YoEight if you have time can you review the changes I made since your review.

**Review by YoEight — APPROVED** [review]

**Comment by YoEight** [comment]
@bweston92 my bad, I thought I already approved it.

**Comment by bweston92** [comment]
@YoEight you did, I changed it since you had. Thanks for the merge.

**Pull request merged**
