### PR TITLE
Implement persistent subscriptions

### PR DESCRIPTION
**Pull request by pivonroll**

### CODE REVIEW

**Comment by radovanEmbroker** [comment]
I am working on tests and to refactor Start method to be non-blocking

**Comment by pivonroll** [comment]
I am working on tests and to refactor Start method to be non-blocking.

**Comment by radovanEmbroker** [comment]
@hayley-jean Could you maybe restart the build job or regenerate the access token for CI? 
Workflow could not fetch the docker image.
I had the similar issue on my local machine and I resolved it by generating a new access token. It just would not budge with my older token.

**Comment by pivonroll** [comment]
@hayley-jean I just noticed that this PR has 8k lines of code. Do you maybe want me to stop here? Scope seems like it is as big as it is.
I have tests with persistent subscriptions for streams.
I haven't got any luck with creating persistent subscriptions to all. I thought to add this in next PR if you agree?

**Comment by hayley-jean** [comment]
@pivonroll Thanks for the hard work!

I agree that it would be best to do subscriptions to $all in a separate PR to make it easier for us to test and review 😄 
Are you happy for us to start reviewing this PR?

**Comment by pivonroll** [comment]
Np :)
You can start the review.

**Comment by pivonroll** [comment]
Last update: just added a few tests for reading for persistent subscription to a stream.

**Comment by YoEight** [comment]
@pivonroll Thanks for your work.

I got one question. What did you do to format the code? When running the formatting tool locally, `client.go` doesn't change that much (when not taking into account your persistent sub work).

**Comment by pivonroll** [comment]
@YoEight I used [gofumpt](https://github.com/mvdan/gofumpt)

**Comment by pivonroll** [comment]
I disabled the tests which require EventStore version 21.6.0 or greater.

**Review by YoEight — APPROVED** [review]

**Review by pvanbuijtene — APPROVED** [review]

**Comment by pvanbuijtene** [comment]
@pivonroll Thanks for the contribution, much appreciated 👍

**Pull request merged**
