### PR TITLE
Support channel-based read operations.

### PR DESCRIPTION
**Pull request by YoEight**

### CODE REVIEW

**Comment by pvanbuijtene** [comment]
@YoEight the CI fails with `rpc error: code = AlreadyExists desc = Subscription group Group 1 on stream someStream exists`, how is this related to the health check ?

**Review by pvanbuijtene — APPROVED** [review]

**Comment by YoEight** [comment]
@pvanbuijtene It is not the reason for the test failing. That error you are talking about is actually expected:

```
Starting docker container...
Started container with id: 2682eff99655deeacac118abcf830910164d79bf6e7d4e8916281a3bda98de74, name: /peaceful_lewin
Error: /17 10:14:43 [error] unexpected exception: rpc error: code = AlreadyExists desc = Subscription group Group 1 on stream someStream exists.
2021/08/17 10:14:43 [info] Starting a new discovery process
--- PASS: Test_CreatePersistentStreamSubscription_FailsIfAlreadyExists (2.62s)
```

**Comment by YoEight** [comment]
Here's the reason why the CI is failing:
```
Starting docker container...
Started container with id: 1e5b95889ab3717ec49d499607613644d5ad2dab2ac5df7fbbb6557c323d087a, name: /epic_hamilton
2021/08/17 10:15:45 HealthCheck failed. Reason: Get "https://localhost:49225": read tcp [::1]:47648->[::1]:49225: read: connection reset by peer
2021/08/17 10:15:45 Stopping docker resource
FAIL	github.com/EventStore/EventStore-Client-Go/client	108.449s
```

**Comment by pvanbuijtene** [comment]
aah right, thanks for clearing that up 👍

**Review by hayley-jean — CHANGES_REQUESTED** [review]
Could you add some tests for reaching EOF @YoEight? I don't seem to be getting End Of Stream when testing locally, resulting in my reads hanging

**Review by hayley-jean — APPROVED** [review]

**Pull request merged**
